# Generated by Django 5.1.1 on 2024-10-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
