# Generated by Django 5.1.1 on 2024-10-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_products_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='photo',
            new_name='image',
        ),
    ]
